### ISSUE TITLE
Lage video files didn't upload

### ISSUE THREAD

**Issue by AustinGMackell** [ImportantCool/gogonzo#15] opened 2016-07-04 13:13 UTC
Two large video files I tried uploading overnight both failed. Don't think it was my connection this time. Video artefacts will be key.
<img width="2560" alt="screen shot 2016-07-04 at 7 50 48 am" src="https://cloud.githubusercontent.com/assets/15120520/16561072/d3d1128a-41bc-11e6-96cc-c49f2e4e50f8.png">

**Comment by motatoes** [comment] 2016-07-04 22:06
what's the file type you were tyring to upload? (mp4, avi ...)

**Comment by AustinGMackell** [comment] 2016-07-05 03:29
MPEG-4 movie

**Comment by AustinGMackell** [comment] 2016-07-05 03:30
One shorter clip that did upload was MOV. I didn't compress it into MPEG because it was so short. The others would have been gigabites in MOV:

**Comment by motatoes** [comment] 2016-07-06 21:38
Uploading mp4 files should work now (please verify)

**Comment by AustinGMackell** [comment] 2016-07-06 22:23
So are MPEG-4 and MP4 the same thing?

**Comment by AustinGMackell** [comment] 2016-07-07 04:20
hey they didn't work but also my connection has been dropping out all night, real bad... so it could just be that-

**Comment by motatoes** [comment] 2016-07-07 09:04
Can you send me the file that you are trying to upload via Dropbox or something ?

**Comment by AustinGMackell** [comment] 2016-07-07 14:53
Sure... also let you know I tried again overnight, as in set it to upload and went to bed. Usually through the night's off-peak times i get decent connectivity. No joy. Will send the file now.

**Comment by motatoes** [comment] 2016-07-07 20:56
waiting .. @AustinGMackell

**Comment by AustinGMackell** [comment] 2016-07-08 20:56
Sorry.... net is being terrible recently... I keep having to pause the synch (sending to dropbox) to get anything done while I'm at my desk and then forgetting to unpause when I am away from the desk.

**Comment by motatoes** [comment] 2016-07-16 19:51
I've [added the video file you sent me](http://gogonzo.uk.to/artefacts/9) successfully so I suppose the issue is resolved

**Comment by motatoes** [comment] 2016-08-03 22:12
Closing this for now because as far as i can tell its fixed

**Closed by motatoes** 2016-08-03 22:12 UTC
Labels: bug
